/*
 * Please do not edit this file.
 * It was generated by /home/kimelman/etc/gsql/gl/etc/rpcgen-sh
 */

#include "include.h"

#ifdef DIRECT_MODE

#ifndef RPCGEN_ACTION
#define RPCGEN_ACTION 
#endif





gss_server_t *server = NULL;

static void
gss_server_exit(void)
{
    deallocate_gss_server(server);
}

int 
main(
#ifdef RPCMAIN_PROTO
    int argc,
    char** argv
#else
    void
#endif
    )
{
  if (server==NULL) {
    ATEXIT(gss_server_exit);
    server = allocate_gss_server ();

  }
  return run_gss_server (server, -2); /* wait foreever */
}

#else

/*
 * Please do not edit this file.
 * It was generated by /home/kimelman/etc/gsql/gl/etc/rpcgen-sh
 */

#include "include.h"

#ifdef DIRECT_MODE

#ifndef RPCGEN_ACTION
#define RPCGEN_ACTION 
#endif





gss_server_t *server = NULL;

static void
gss_server_exit(void)
{
    deallocate_gss_server(server);
}

int 
main(
#ifdef RPCMAIN_PROTO
    int argc,
    char** argv
#else
    void
#endif
    )
{
  if (server==NULL) {
    ATEXIT(gss_server_exit);
    server = allocate_gss_server ();

  }
  return run_gss_server (server, -2); /* wait foreever */
}

#else



#endif

#endif
