/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "gsqltrn.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif
#define main run_server
#define RPC_SVC_FG
#undef GSQL_TRN
#define GSQL_TRN rpc_program_id
extern long rpc_program_id;

static void
gsql_trn_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		init_params_t init_comp_1_arg;
		stmt_info_t compile_1_arg;
		seg_del_t del_segment_1_arg;
		link_cursor_t link_cursor_1_arg;
		string_t load_module_1_arg;
		insn_t execute_stmt_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case INIT_COMP:
		_xdr_argument = (xdrproc_t) xdr_init_params_t;
		_xdr_result = (xdrproc_t) xdr_result_t;
		local = (char *(*)(char *, struct svc_req *)) init_comp_1_svc;
		break;

	case COMPILE:
		_xdr_argument = (xdrproc_t) xdr_stmt_info_t;
		_xdr_result = (xdrproc_t) xdr_result_t;
		local = (char *(*)(char *, struct svc_req *)) compile_1_svc;
		break;

	case DEL_SEGMENT:
		_xdr_argument = (xdrproc_t) xdr_seg_del_t;
		_xdr_result = (xdrproc_t) xdr_result_t;
		local = (char *(*)(char *, struct svc_req *)) del_segment_1_svc;
		break;

	case LINK_CURSOR:
		_xdr_argument = (xdrproc_t) xdr_link_cursor_t;
		_xdr_result = (xdrproc_t) xdr_result_t;
		local = (char *(*)(char *, struct svc_req *)) link_cursor_1_svc;
		break;

	case LOAD_MODULE:
		_xdr_argument = (xdrproc_t) xdr_string_t;
		_xdr_result = (xdrproc_t) xdr_result_t;
		local = (char *(*)(char *, struct svc_req *)) load_module_1_svc;
		break;

	case EXECUTE_STMT:
		_xdr_argument = (xdrproc_t) xdr_insn_t;
		_xdr_result = (xdrproc_t) xdr_result_t;
		local = (char *(*)(char *, struct svc_req *)) execute_stmt_1_svc;
		break;

	case DB_CREATE:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_result_t;
		local = (char *(*)(char *, struct svc_req *)) db_create_1_svc;
		break;

	case RETRY:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_result_t;
		local = (char *(*)(char *, struct svc_req *)) retry_1_svc;
		break;

	case IS_RPC_READY:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) is_rpc_ready_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (GSQL_TRN, BETA0);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, GSQL_TRN, BETA0, gsql_trn_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GSQL_TRN, BETA0, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, GSQL_TRN, BETA0, gsql_trn_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GSQL_TRN, BETA0, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
