ALTER SCHEMA AUTHORIZATION INFORMATION_SCHEMA

CREATE VIEW COLUMN_PRIVILEGES
       AS ( SELECT
          GRANTOR, GRANTEE, COLNO, UNTABID, COLAUTH
       FROM   DEFINITION_SCHEMA.SYSCOLAUTH
       WHERE   GRANTEE IN ('PUBLIC', USER )
            OR GRANTOR = USER
       )


GRANT SELECT ON COLUMN_PRIVILEGES       TO PUBLIC
