/* generated by /home/gunter/GM_DATABASES/DBMS/GnuSQL/gnusql-0.7b6.1/etc/rpcgen-sh /usr/bin/rpcgen . /home/gunter/GM_DATABASES/DBMS/GnuSQL/gnusql-0.7b6.1/src/include /home/gunter/GM_DATABASES/DBMS/GnuSQL/gnusql-0.7b6.1/src/main/gsqltrn.x at Mon Mar  6 20:18:56 EST 2017*/
# include "conn_handler.h"
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GSQLTRN_H_RPCGEN
#define _GSQLTRN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *string_t;

typedef struct {
	u_int init_params_t_len;
	string_t *init_params_t_val;
} init_params_t;

struct stmt_info_t {
	string_t stmt;
	string_t stmt_name;
	int bline;
	struct stmt_info_t *next;
};
typedef struct stmt_info_t stmt_info_t;

struct prep_elem_t {
	int type;
	int length;
	int scale;
	string_t name;
	string_t ind_name;
	int nullable;
};
typedef struct prep_elem_t prep_elem_t;

typedef struct {
	u_int descr_t_len;
	prep_elem_t *descr_t_val;
} descr_t;

struct compiled_object_t {
	struct compiled_object_t *next;
	descr_t descr_in;
	descr_t descr_out;
	int object;
	string_t cursor_name;
	string_t table_name;
	string_t table_owner;
};
typedef struct compiled_object_t compiled_object_t;

struct call_subst_t {
	string_t proc_name;
	descr_t interface;
	descr_t in_sql_parm;
	descr_t out_sql_parm;
	int object;
	int method;
	string_t jmp_on_error;
	string_t jmp_on_eofscan;
};
typedef struct call_subst_t call_subst_t;

struct call_t {
	struct call_t *next;
	struct call_subst_t *subst;
};
typedef struct call_t call_t;

struct file_buf_t {
	string_t ext;
	string_t text;
	struct file_buf_t *next;
};
typedef struct file_buf_t file_buf_t;
#define COMP_STATIC 1
#define COMP_DYNAMIC_CURSOR 2
#define COMP_DYNAMIC_SIMPLE 3

struct comp_data_t {
	int comp_type;
	union {
		string_t module;
		int seg_ptr;
		int segm;
	} comp_data_t_u;
};
typedef struct comp_data_t comp_data_t;

struct compiled_t {
	int errors;
	file_buf_t *bufs;
	compiled_object_t *objects;
	call_t *calls;
	comp_data_t stored;
};
typedef struct compiled_t compiled_t;

struct link_cursor_t {
	string_t cursor_name;
	string_t stmt_name;
	int segment;
};
typedef struct link_cursor_t link_cursor_t;

struct seg_del_t {
	int segment;
	struct {
		u_int seg_vadr_len;
		int *seg_vadr_val;
	} seg_vadr;
};
typedef struct seg_del_t seg_del_t;

struct data {
	int type;
	union {
		struct {
			u_int Str_len;
			char *Str_val;
		} Str;
		short Shrt;
		int Int;
		int Lng;
		float Flt;
		double Dbl;
	} data_u;
};
typedef struct data data;

struct parm_t {
	data value;
	int indicator;
};
typedef struct parm_t parm_t;

typedef struct {
	u_int parm_row_t_len;
	parm_t *parm_row_t_val;
} parm_row_t;
#define RET_COMP 1
#define RET_ROW 2
#define RET_TBL 3
#define RET_SEG 4
#define RET_VOID 0

struct return_data {
	int rett;
	union {
		compiled_t comp_ret;
		parm_row_t row;
		struct {
			u_int tbl_len;
			parm_row_t *tbl_val;
		} tbl;
		int segid;
	} return_data_u;
};
typedef struct return_data return_data;

struct result_t {
	int sqlcode;
	return_data info;
};
typedef struct result_t result_t;

struct insn_t {
	int vadr_segm;
	int sectnum;
	int command;
	int options;
	parm_row_t parms;
	struct insn_t *next;
};
typedef struct insn_t insn_t;
extern result_t gsqltrn_rc;

#define GSQL_TRN 0x40000010
extern struct rpcgen_table gsql_trn_1_table[];
extern gsql_trn_1_nproc;
#define BETA0 1

#if defined(__STDC__) || defined(__cplusplus)
#define INIT_COMP 1
extern  result_t * init_comp_1(init_params_t *, gss_client_t *);
extern  result_t * init_comp_1_svc(init_params_t *, struct svc_req *);
#define COMPILE 2
extern  result_t * compile_1(stmt_info_t *, gss_client_t *);
extern  result_t * compile_1_svc(stmt_info_t *, struct svc_req *);
#define DEL_SEGMENT 3
extern  result_t * del_segment_1(seg_del_t *, gss_client_t *);
extern  result_t * del_segment_1_svc(seg_del_t *, struct svc_req *);
#define LINK_CURSOR 4
extern  result_t * link_cursor_1(link_cursor_t *, gss_client_t *);
extern  result_t * link_cursor_1_svc(link_cursor_t *, struct svc_req *);
#define LOAD_MODULE 5
extern  result_t * load_module_1(string_t *, gss_client_t *);
extern  result_t * load_module_1_svc(string_t *, struct svc_req *);
#define EXECUTE_STMT 6
extern  result_t * execute_stmt_1(insn_t *, gss_client_t *);
extern  result_t * execute_stmt_1_svc(insn_t *, struct svc_req *);
#define DB_CREATE 7
extern  result_t * db_create_1(void *, gss_client_t *);
extern  result_t * db_create_1_svc(void *, struct svc_req *);
#define RETRY 8
extern  result_t * retry_1(void *, gss_client_t *);
extern  result_t * retry_1_svc(void *, struct svc_req *);
#define IS_RPC_READY 9
extern  int * is_rpc_ready_1(void *, gss_client_t *);
extern  int * is_rpc_ready_1_svc(void *, struct svc_req *);
extern int gsql_trn_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define INIT_COMP 1
extern  result_t * init_comp_1();
extern  result_t * init_comp_1_svc();
#define COMPILE 2
extern  result_t * compile_1();
extern  result_t * compile_1_svc();
#define DEL_SEGMENT 3
extern  result_t * del_segment_1();
extern  result_t * del_segment_1_svc();
#define LINK_CURSOR 4
extern  result_t * link_cursor_1();
extern  result_t * link_cursor_1_svc();
#define LOAD_MODULE 5
extern  result_t * load_module_1();
extern  result_t * load_module_1_svc();
#define EXECUTE_STMT 6
extern  result_t * execute_stmt_1();
extern  result_t * execute_stmt_1_svc();
#define DB_CREATE 7
extern  result_t * db_create_1();
extern  result_t * db_create_1_svc();
#define RETRY 8
extern  result_t * retry_1();
extern  result_t * retry_1_svc();
#define IS_RPC_READY 9
extern  int * is_rpc_ready_1();
extern  int * is_rpc_ready_1_svc();
extern int gsql_trn_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_string_t (XDR *, string_t*);
extern  bool_t xdr_init_params_t (XDR *, init_params_t*);
extern  bool_t xdr_stmt_info_t (XDR *, stmt_info_t*);
extern  bool_t xdr_prep_elem_t (XDR *, prep_elem_t*);
extern  bool_t xdr_descr_t (XDR *, descr_t*);
extern  bool_t xdr_compiled_object_t (XDR *, compiled_object_t*);
extern  bool_t xdr_call_subst_t (XDR *, call_subst_t*);
extern  bool_t xdr_call_t (XDR *, call_t*);
extern  bool_t xdr_file_buf_t (XDR *, file_buf_t*);
extern  bool_t xdr_comp_data_t (XDR *, comp_data_t*);
extern  bool_t xdr_compiled_t (XDR *, compiled_t*);
extern  bool_t xdr_link_cursor_t (XDR *, link_cursor_t*);
extern  bool_t xdr_seg_del_t (XDR *, seg_del_t*);
extern  bool_t xdr_data (XDR *, data*);
extern  bool_t xdr_parm_t (XDR *, parm_t*);
extern  bool_t xdr_parm_row_t (XDR *, parm_row_t*);
extern  bool_t xdr_return_data (XDR *, return_data*);
extern  bool_t xdr_result_t (XDR *, result_t*);
extern  bool_t xdr_insn_t (XDR *, insn_t*);

#else /* K&R C */
extern bool_t xdr_string_t ();
extern bool_t xdr_init_params_t ();
extern bool_t xdr_stmt_info_t ();
extern bool_t xdr_prep_elem_t ();
extern bool_t xdr_descr_t ();
extern bool_t xdr_compiled_object_t ();
extern bool_t xdr_call_subst_t ();
extern bool_t xdr_call_t ();
extern bool_t xdr_file_buf_t ();
extern bool_t xdr_comp_data_t ();
extern bool_t xdr_compiled_t ();
extern bool_t xdr_link_cursor_t ();
extern bool_t xdr_seg_del_t ();
extern bool_t xdr_data ();
extern bool_t xdr_parm_t ();
extern bool_t xdr_parm_row_t ();
extern bool_t xdr_return_data ();
extern bool_t xdr_result_t ();
extern bool_t xdr_insn_t ();

#endif /* K&R C */
struct RPCGEN_TABLE_GSQLTRN {
	char	*(*proc)();
	xdrproc_t	xdr_arg;
	unsigned	len_arg;
	xdrproc_t	xdr_res;
	unsigned	len_res;
};

#ifdef __cplusplus
}
#endif

#endif /* !_GSQLTRN_H_RPCGEN */
