ALTER SCHEMA AUTHORIZATION INFORMATION_SCHEMA

CREATE VIEW VIEWS   ( TABLE_NAME )
       AS ( SELECT
          TABNAME 
       FROM  DEFINITION_SCHEMA.SYSTABLES
       WHERE TABTYPE = 'V' )
       

GRANT SELECT ON VIEWS                   TO PUBLIC
