ALTER SCHEMA AUTHORIZATION INFORMATION_SCHEMA

CREATE VIEW REFERENTIAL_CONSTRAINTS
       AS  ( SELECT  
             TABFROM, TABTO, NCOLS
       FROM  DEFINITION_SCHEMA.SYSREFCONSTR
       )

GRANT SELECT ON REFERENTIAL_CONSTRAINTS TO PUBLIC
