ALTER SCHEMA AUTHORIZATION INFORMATION_SCHEMA

CREATE VIEW TABLES  ( TABLE_NAME ,TABLE_TYPE, NUM_COLUMNS, NUM_INDEXES )
       AS
     (
       SELECT  T.TABNAME, T.TABTYPE, T.NCOLS , -1
       FROM  DEFINITION_SCHEMA.SYSTABLES T
       WHERE T.UNTABID IN 
            ( SELECT UNTABID
             FROM   DEFINITION_SCHEMA.SYSTABAUTH
             WHERE  GRANTEE IN ('PUBLIC', USER ) 
            )
     )

GRANT SELECT ON TABLES                  TO PUBLIC
